# Generated by Django 5.2.1 on 2025-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_seasonproduct_price_1_seasonproduct_price_10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_1',
            new_name='price_double_stem_1',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_10',
            new_name='price_double_stem_10',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_11',
            new_name='price_double_stem_11',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_12',
            new_name='price_double_stem_12',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_13',
            new_name='price_double_stem_13',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_14',
            new_name='price_double_stem_14',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_15',
            new_name='price_double_stem_15',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_16',
            new_name='price_double_stem_16',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_17',
            new_name='price_double_stem_17',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_18',
            new_name='price_double_stem_18',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_2',
            new_name='price_double_stem_2',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_3',
            new_name='price_double_stem_3',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_4',
            new_name='price_double_stem_4',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_5',
            new_name='price_double_stem_5',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_6',
            new_name='price_double_stem_6',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_7',
            new_name='price_double_stem_7',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_8',
            new_name='price_double_stem_8',
        ),
        migrations.RenameField(
            model_name='seasonproduct',
            old_name='price_9',
            new_name='price_double_stem_9',
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_11',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_13',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_14',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_17',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonproduct',
            name='price_single_stem_9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
