# Generated by Django 5.2.1 on 2025-05-29 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_rename_price_1_seasonproduct_price_double_stem_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonproduct',
            name='waiting_on_room_duration',
            field=models.PositiveIntegerField(default=30, help_text='Oda bekleme süresi', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Oda Bekleme Süresi (Gün)'),
        ),
    ]
