# Generated by Django 5.2.1 on 2025-05-28 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Müşterinin adı', max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(help_text='Müşterinin soyadı', max_length=100, verbose_name='Soyad')),
                ('color', models.CharField(choices=[('#0d5016', 'Koyu Yeşil (A Sınıfı)'), ('#2c9c3e', 'Açık Yeşil (B Sınıfı)'), ('#8bc34a', 'Fıstık Yeşili (C Sınıfı)'), ('#ffeb3b', 'Sarı (D Sınıfı)'), ('#ff9800', 'Sarı-Turuncu (E Sınıfı)'), ('#ff5722', 'Turuncu (F Sınıfı)'), ('#d32f2f', 'Kırmızı (G Sınıfı)')], db_index=True, default='#ffeb3b', help_text='Müşterinin renk seçimi', max_length=10, verbose_name='Renk')),
                ('phone_number', models.CharField(help_text='5XXXXXXXXX formatında (Türkiye)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon numarası 5XXXXXXXXX formatında olmalıdır', regex='^5[0-9]{9}$')], verbose_name='Telefon Numarası')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(db_index=True, max_length=50, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
                ('address', models.TextField(help_text='Detaylı adres bilgisi', max_length=500, verbose_name='Adres')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Müşteri aktif mi?', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'db_table': 'customers_customer',
                'ordering': ['-created_at', 'first_name', 'last_name'],
                'indexes': [models.Index(fields=['city', 'district'], name='city_district_idx'), models.Index(fields=['is_active', 'created_at'], name='active_created_idx'), models.Index(fields=['first_name', 'last_name'], name='full_name_idx'), models.Index(fields=['created_by', 'is_active'], name='creator_active_idx'), models.Index(fields=['color', 'is_active'], name='color_active_idx'), models.Index(fields=['color', 'city'], name='color_city_idx')],
            },
        ),
    ]
