# Generated by Django 5.2.1 on 2025-06-01 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('seasons', '0004_seasonproduct_waiting_on_room_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('rootstock_planting_sent', 'Anaç Gönderildi'), ('rootstock_planting_confirmed', 'Anaç Onaylandı'), ('rootstock_planting_planted', 'Anaç Ekildi'), ('scion_planting_sent', 'Kalem Gönderildi'), ('scion_planting_confirmed', 'Kalem Onaylandı'), ('scion_planting_planted', 'Kalem Ekildi'), ('grafting_sent', 'Aşıya Gönderildi'), ('grafting_confirmed', 'Aşı Onaylandı'), ('grafting_planted', 'Aşı Ekildi'), ('head_formation_sent', 'Kafa Kesime Gönderildi'), ('head_formation_confirmed', 'Kafa Kesime Onaylandı'), ('head_formation_formed', 'Kafa Kesime Ekildi'), ('cutting_sent', 'Bekleme Odasına Gönderildi'), ('cutting_confirmed', 'Bekleme Odasına Onaylandı'), ('cutting_cut', 'Bekleme Odasında'), ('ready_for_shipment', 'Sevkiyata Hazır')], default='rootstock_planting_sent', max_length=30, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('confirmed', 'Onaylandı'), ('waiting', 'Bekliyor'), ('awaiting_shipment', 'Sevkiyat Bekliyor'), ('shipped', 'Sevkiyatta'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Taslak'), ('confirmed', 'Onaylandı'), ('waiting', 'Bekliyor'), ('awaiting_shipment', 'Sevkiyat Bekliyor'), ('shipped', 'Sevkiyatta'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], max_length=20, null=True, verbose_name='Önceki Durum'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('confirmed', 'Onaylandı'), ('waiting', 'Bekliyor'), ('awaiting_shipment', 'Sevkiyat Bekliyor'), ('shipped', 'Sevkiyatta'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], max_length=20, verbose_name='Yeni Durum'),
        ),
        migrations.CreateModel(
            name='PlantingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(help_text='Otomatik oluşturulur', max_length=20, unique=True, verbose_name='Talep Numarası')),
                ('planting_type', models.CharField(choices=[('rootstock', 'Anaç Ekimi'), ('scion', 'Kalem Ekimi')], help_text='Anaç mı kalem ekimi mi?', max_length=10, verbose_name='Ekim Türü')),
                ('requested_planting_date', models.DateField(help_text='Bu tarihte ekim yapılması isteniyor', verbose_name='Talep Edilen Ekim Tarihi')),
                ('sent_to_planting_date', models.DateTimeField(blank=True, help_text='Ekim bölümüne gönderildiği tarih', null=True, verbose_name='Ekime Gönderilme Tarihi')),
                ('confirmed_date', models.DateTimeField(blank=True, help_text='Ekim bölümü tarafından onaylandığı tarih', null=True, verbose_name='Onaylanma Tarihi')),
                ('actual_planting_date', models.DateField(blank=True, help_text='Fiili olarak ekildiği tarih', null=True, verbose_name='Gerçek Ekim Tarihi')),
                ('completion_date', models.DateTimeField(blank=True, help_text='İşlemin tamamlandığı tarih', null=True, verbose_name='Tamamlanma Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Ekime Gönderildi'), ('confirmed', 'Ekim Onaylandı'), ('planted', 'Ekildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=15, verbose_name='Durum')),
                ('planting_location', models.CharField(blank=True, help_text='Hangi sera, blok, sıra vs.', max_length=100, null=True, verbose_name='Ekim Lokasyonu')),
                ('planting_area', models.CharField(blank=True, help_text='A Serası, B Bloku vs.', max_length=50, null=True, verbose_name='Ekim Alanı')),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='Bu talepteki toplam fide sayısı', verbose_name='Toplam Miktar')),
                ('total_viol_count', models.PositiveIntegerField(default=0, help_text='Bu talepteki toplam viol sayısı', verbose_name='Toplam Viol Sayısı')),
                ('notes', models.TextField(blank=True, help_text='Ekim talebi ile ilgili notlar', null=True, verbose_name='Notlar')),
                ('internal_notes', models.TextField(blank=True, help_text='Dahili kullanım için notlar', null=True, verbose_name='İç Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_planting_requests', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planting_requests', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('order_items', models.ManyToManyField(help_text='Bu talebe dahil sipariş kalemleri', related_name='planting_requests', to='orders.orderitem', verbose_name='Sipariş Kalemleri')),
                ('planted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planted_requests', to=settings.AUTH_USER_MODEL, verbose_name='Eken Kişi')),
                ('rootstock', models.ForeignKey(blank=True, help_text='Anaçsız ürünler için boş', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.rootstock', verbose_name='Anaç')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_requests', to='seasons.season', verbose_name='Sezon')),
                ('variety', models.ForeignKey(help_text='Ekimi yapılacak çeşit', on_delete=django.db.models.deletion.CASCADE, to='products.variety', verbose_name='Çeşit')),
            ],
            options={
                'verbose_name': 'Ekim Talep Kartı',
                'verbose_name_plural': 'Ekim Talep Kartları',
                'db_table': 'orders_plantingrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantingRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Bekliyor'), ('sent', 'Ekime Gönderildi'), ('confirmed', 'Ekim Onaylandı'), ('planted', 'Ekildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], max_length=15, null=True, verbose_name='Önceki Durum')),
                ('to_status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Ekime Gönderildi'), ('confirmed', 'Ekim Onaylandı'), ('planted', 'Ekildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], max_length=15, verbose_name='Yeni Durum')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Değişim Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('location_info', models.CharField(blank=True, help_text='Değişiklik sırasındaki lokasyon bilgisi', max_length=200, null=True, verbose_name='Lokasyon Bilgisi')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren')),
                ('planting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.plantingrequest', verbose_name='Ekim Talebi')),
            ],
            options={
                'verbose_name': 'Ekim Talep Geçmişi',
                'verbose_name_plural': 'Ekim Talep Geçmişleri',
                'db_table': 'orders_plantingrequesthistory',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='plantingrequest',
            index=models.Index(fields=['variety', 'rootstock'], name='planting_product_idx'),
        ),
        migrations.AddIndex(
            model_name='plantingrequest',
            index=models.Index(fields=['season', 'planting_type'], name='planting_season_type_idx'),
        ),
        migrations.AddIndex(
            model_name='plantingrequest',
            index=models.Index(fields=['status'], name='planting_status_idx'),
        ),
        migrations.AddIndex(
            model_name='plantingrequest',
            index=models.Index(fields=['requested_planting_date'], name='planting_date_idx'),
        ),
        migrations.AddIndex(
            model_name='plantingrequest',
            index=models.Index(fields=['planting_area'], name='planting_area_idx'),
        ),
        migrations.AddConstraint(
            model_name='plantingrequest',
            constraint=models.UniqueConstraint(fields=('variety', 'rootstock', 'planting_type', 'requested_planting_date', 'season'), name='unique_planting_request'),
        ),
    ]
