# Generated by Django 5.2.1 on 2025-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingrequest',
            name='planting_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Gerçekte ekilecek fide sayısı (kullanıcı girer)', verbose_name='Ekim Adedi'),
        ),
    ]
