# Generated by Django 5.2.1 on 2025-06-01 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_plantingrequest_planting_quantity'),
        ('products', '0001_initial'),
        ('seasons', '0004_seasonproduct_waiting_on_room_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plantingrequest',
            name='unique_planting_request',
        ),
        migrations.RemoveIndex(
            model_name='plantingrequest',
            name='planting_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='plantingrequest',
            name='planting_season_type_idx',
        ),
        migrations.AlterField(
            model_name='plantingrequest',
            name='variety',
            field=models.ForeignKey(blank=True, help_text='Ana çeşit (birden fazla çeşit olabilir)', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variety', verbose_name='Çeşit'),
        ),
        migrations.AddIndex(
            model_name='plantingrequest',
            index=models.Index(fields=['rootstock', 'planting_type'], name='planting_rootstock_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='plantingrequest',
            constraint=models.UniqueConstraint(fields=('rootstock', 'planting_type', 'requested_planting_date', 'season'), name='unique_planting_request'),
        ),
    ]
