# Generated by Django 5.2.1 on 2025-05-28 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örnek: Kurumsal, Türkiye, İtalya, Almanya', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Marka Adı')),
                ('price_per_packet', models.DecimalField(decimal_places=2, help_text='Tohum paket fiyatı (TL)', max_digits=10, verbose_name='Tohum Paket Fiyatı')),
                ('seeds_per_packet', models.PositiveIntegerField(help_text='Bir pakette kaç adet tohum var', verbose_name='Paket Başına Tohum Sayısı')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bu marka aktif olarak kullanılıyor mu?', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Tohum Markası',
                'verbose_name_plural': 'Tohum Markaları',
                'db_table': 'products_seedbrand',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='seedbrand_name_idx'), models.Index(fields=['is_active'], name='seedbrand_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örnek: Domates, Aşılı Domates, Biber, Patlıcan', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Tür Adı')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bu tür aktif olarak kullanılıyor mu?', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Tür',
                'verbose_name_plural': 'Türler',
                'db_table': 'products_species',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='species_name_idx'), models.Index(fields=['is_active'], name='species_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rootstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örnek: M9, M26, MM106', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Anaç Adı')),
                ('vigor_level', models.CharField(blank=True, choices=[('low', 'Düşük Vigör'), ('medium', 'Orta Vigör'), ('high', 'Yüksek Vigör')], help_text='Anacın büyüme gücü', max_length=20, null=True, verbose_name='Vigör Seviyesi')),
                ('description', models.TextField(blank=True, help_text='Anaç hakkında detaylı bilgiler', null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bu anaç aktif olarak kullanılıyor mu?', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('species', models.ForeignKey(help_text='Bu anacın ait olduğu tür', on_delete=django.db.models.deletion.CASCADE, related_name='rootstocks', to='products.species', verbose_name='Tür')),
            ],
            options={
                'verbose_name': 'Anaç',
                'verbose_name_plural': 'Anaçlar',
                'db_table': 'products_rootstock',
                'ordering': ['species__name', 'name'],
                'indexes': [models.Index(fields=['name'], name='rootstock_name_idx'), models.Index(fields=['species', 'name'], name='rootstock_species_name_idx'), models.Index(fields=['is_active'], name='rootstock_active_idx'), models.Index(fields=['vigor_level'], name='rootstock_vigor_idx')],
                'unique_together': {('species', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örnek: Starking, Granny Smith, Golden Delicious', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Çeşit Adı')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bu çeşit aktif olarak kullanılıyor mu?', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('seed_brand', models.ForeignKey(help_text='Bu çeşidin ait olduğu tohum markası', on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='products.seedbrand', verbose_name='Tohum Markası')),
                ('species', models.ForeignKey(help_text='Bu çeşidin ait olduğu tür', on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='products.species', verbose_name='Tür')),
            ],
            options={
                'verbose_name': 'Çeşit',
                'verbose_name_plural': 'Çeşitler',
                'db_table': 'products_variety',
                'ordering': ['species__name', 'name'],
                'indexes': [models.Index(fields=['name'], name='variety_name_idx'), models.Index(fields=['species', 'name'], name='variety_species_name_idx'), models.Index(fields=['is_active'], name='variety_active_idx'), models.Index(fields=['seed_brand'], name='variety_seedbrand_idx')],
                'unique_together': {('species', 'name')},
            },
        ),
    ]
